### ISSUE TITLE
Incorrect guestbook URL in README

### ISSUE THREAD

**Issue by JonathanGin52** [sriharikapu/sriharikapu#1]
Your URL in the README links to the template file for a guestbook entry. In my opinion, a more sensible approach would be to link to the `new issue` page, with the template prepopulated. 
Ie: [`https://github.com/sriharikapu/sriharikapu/issues/new?template=Guestbook_entry.md&title=Adding+<username>+to+guestbook`](https://github.com/sriharikapu/sriharikapu/issues/new?template=Guestbook_entry.md&title=Adding+<username>+to+guestbook)

**Comment by sriharikapu** [comment]
Awesome! Thank you so much @JonathanGin52 🎉

I had update the URL in the README to new issue as recommended by you..
